### ISSUE TITLE
RFE: metric system

### ISSUE THREAD

**Issue by hhielscher** [patik/dof#18]
Please support the metric system (meters instead of feet).

**Comment by Gabriele-LS** [comment]
Yes, that would be awesome!

**Comment by patik** [comment]
This is a great idea and I plan to implement it.

First I want to modernize the project—it should be a proper node module that one can install via NPM, it should have tests and export types, etc. I will do that and make metric the new default, with an option to use imperial units.

**Comment by Gabriele-LS** [comment]
Great news! Thanks for your effort.

**Comment by patik** [comment]
This was partially addressed with #19. The Node module now uses metric, but I still have to update the web app GUI.

**Comment by Gabriele-LS** [comment]
> This was partially addressed with #19. The Node module now uses metric, but I still have to update the web app GUI.

This is great. I can't wait to use the new version. But I don't know what to do with the node module, I think I need to wait for the web app update. Thank you very much for your effort.

**Comment by patik** [comment]
The web app has been updated: http://patik.com/dof/
